server
{
    Name    server
    Port    1236
    Host    127.0.0.1
    Host    192.168.1.1 #Duplicate Host field

    Client-max-body-size    2048

    route
    {
        Allowed GET
        Allowed PUT
        Forbidden DELETE
        Match   /truc
        Location    html/
        Listing ON
    }
}
