server
{
    Name    server
    Port    1236
    Host    127.0.0.1
    # Missing Client-max-body-size field

    route
    {
        Allowed GET
        Allowed PUT
        Forbidden DELETE
        Match   /truc
        Location    html/
        Listing ON
    }
}
