server
{
    Name    server
    Port    1236
    Host    127.0.0.1

    Client-max-body-size    2048

    route
    {
        Allowed GET
        Allowed INVALID_METHOD #Invalid Allowed method
        Forbidden DELETE
        Match   /truc
        Location    html/
        Listing ON
    }
}
